spring:
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:postgresql://localhost:5432/exclusio
    username: vincentdarcq
    password: uTLhewpTC12;
    driver-class-name: org.postgresql.Driver

url: http://localhost:8080
